# Generated by Django 5.1.3 on 2024-11-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_farm_farmer_id_alter_farmrank_buyer_id_and_more'),
        ('products', '0004_alter_product_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.farm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.subcategory'),
        ),
    ]
